version: '3.3'
services:
  nginx:
     build: ./nginx
     container_name: lnmp_nginx 
     ports: 
       - "8088:80"
     links:
       - "php"
     volumes:
       - /home/zy/docker-lnmp/html:/var/www/html
       - /home/zy/docker-lnmp/nginx/conf/zy.conf:/etc/nginx/conf.d/default.conf
  php:
     build: ./php
     container_name: lnmp_php
     ports:
       - "9001:9000"
     volumes: 
       - ./html/:/var/www/html
     links:
       - "mysql"
  mysql:
     build: ./mysql
     container_name: lnmp_mysql
     ports:
       - "3307:3306"
     volumes:
       - /home/zy/docker-lnmp/mysql/data/:/var/lib/mysql/
     environment:
       MYSQL_ROOT_PASSWORD : root
